module.exports = {
  id: "codeit",
  name: "Code it",
  inputArtifact: "artifact.generate.json",
  outputArtifact: "artifact.codeit.json",
  gate: {
    enabled: true,
    maxVisualDelta: 0.002,
    revertOnRegression: true,
  },
  contracts: [
    { id: "layout/classes/dedupeUtilities", path: "./contracts/layout/classes/dedupeUtilities.js", options: {} },
    { id: "layout/classes/dedupeConflictsHard", path: "./contracts/layout/classes/dedupeConflictsHard.js", options: {} },
    { id: "layout/display/dedupeDisplay", path: "./contracts/layout/display/dedupeDisplay.js", options: {} },
    { id: "style/inline/stripRedundantInlineStyles", path: "./contracts/style/inline/stripRedundantInlineStyles.js", options: {} },
    { id: "layout/wrappers/mergeLayoutSignature", path: "./contracts/layout/wrappers/mergeLayoutSignature.js", options: {} },
    { id: "layout/container/addMxAuto", path: "./contracts/layout/container/addMxAuto.js", options: {} },
    { id: "layout/height/removeFixedHeights", path: "./contracts/layout/height/removeFixedHeights.js", options: {} },
    { id: "layout/underline/normalizeBars", path: "./contracts/layout/underline/normalizeBars.js", options: {} },
    { id: "layout/width/fluidizeFixedRem", path: "./contracts/layout/width/fluidizeFixedRem.js", options: {} },
    { id: "layout/width/dedupeWidths", path: "./contracts/layout/width/dedupeWidths.js", options: {} },
    { id: "layout/width/enforceWidthIntent", path: "./contracts/layout/width/enforceWidthIntent.js", options: {} },
    { id: "layout/width/innerWrapperFixedWidthToMax", path: "./contracts/layout/width/innerWrapperFixedWidthToMax.js", options: {} },
    { id: "layout/width/widthRedundancyCollapseContract", path: "./contracts/layout/width/widthRedundancyCollapseContract.js", options: {} },
    { id: "layout/text/textFixedWidthGuardContract", path: "./contracts/layout/text/textFixedWidthGuardContract.js", options: {} },
    { id: "layout/root/removeFrameDimensions", path: "./contracts/layout/root/removeFrameDimensions.js", options: {} },
    { id: "layout/section/enforceMobileVerticalPadding", path: "./contracts/layout/section/enforceMobileVerticalPadding.js", options: {} },
    { id: "layout/text/nowrapGuard", path: "./contracts/layout/text/nowrapGuard.js", options: {} },
    { id: "layout/text/shrinkGuard", path: "./contracts/layout/text/shrinkGuard.js", options: {} },
    { id: "layout/align/centerCardContent", path: "./contracts/layout/align/centerCardContent.js", options: {} },
    { id: "layout/grid/upgradeToGridForMatrices", path: "./contracts/layout/grid/upgradeToGridForMatrices.js", options: {} },
    { id: "layout/layoutModel/inferGridFromRepeatingCards", path: "./contracts/layout/layoutModel/inferGridFromRepeatingCards.js", options: {} },
    { id: "layout/grid/stripFlexChildSizing", path: "./contracts/layout/grid/stripFlexChildSizing.js", options: {} },
    { id: "layout/wrappers/flattenRedundant", path: "./contracts/layout/wrappers/flattenRedundant.js", options: {} },
    { id: "layout/cleanup/previewNormalize", path: "./contracts/layout/cleanup/previewNormalize.js", options: {} },
    { id: "semantics/landmarks/upgradeLandmarks", path: "./contracts/semantics/landmarks/upgradeLandmarks.js", options: {} },
    { id: "semantics/interactive/cardToLinkOrButton", path: "./contracts/semantics/interactive/cardToLinkOrButton.js", options: {} },
    { id: "semantics/interactive/preventNestedInteractive", path: "./contracts/semantics/interactive/preventNestedInteractive.js", options: {} },
    { id: "layout/section/containerNormalize", path: "./contracts/layout/section/containerNormalize.js", options: {} },
  ],
};
